p, admin, /admin/*, *
p, admin, /app/*, *
p, user, /app/v1/blog/articles, read
p, user, /app/v1/blog/articles/*, read
p, user, /app/v1/blog/categories, read
p, user, /app/v1/blog/tags, read
p, user, /app/v1/blog/articles/*/comments, read
p, user, /app/v1/blog/articles/*/comments, write
g, admins, admin
g, users, user
